use_frameworks!

platform :ios, '10.0'

target 'AddressBookModule_Example' do
  pod 'AddressBookModule', :path => '../'

  target 'AddressBookModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
